services:
  masareef-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: masareef-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.masareef-api.rule=Host(`api-masareef.agharib.com`)"
      - "traefik.http.routers.masareef-api.entrypoints=web"
      - "traefik.http.services.masareef-api.loadbalancer.server.port=8000"
    networks:
      - dokploy-network
      - masareef

  masareef-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: masareef-web
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.masareef-web.rule=Host(`masareef.agharib.com`)"
      - "traefik.http.routers.masareef-web.entrypoints=web"
      - "traefik.http.services.masareef-web.loadbalancer.server.port=3000"
    networks:
      - dokploy-network
      - masareef
    depends_on:
      - masareef-api

networks:
  dokploy-network:
    external: true
  masareef:
    driver: bridge
