"""add financial institutions and update accounts

Revision ID: 1b243df27c85
Revises: phase3_006
Create Date: 2026-04-05 11:56:26.836796

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b243df27c85"
down_revision: str | Sequence[str] | None = "phase3_006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_institutions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=False),
        sa.Column("name_ar", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("bank", "bnpl", "digital_wallet_provider", name="institutiontype"),
            nullable=False,
        ),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("bic_swift", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=3), server_default="EG", nullable=False),
        sa.Column("is_predefined", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_popular", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reconciliation_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("expected_balance_minor", sa.BigInteger(), nullable=False),
        sa.Column("actual_balance_minor", sa.BigInteger(), nullable=False),
        sa.Column("adjustment_minor", sa.BigInteger(), nullable=False),
        sa.Column("reconciliation_date", sa.Date(), nullable=False),
        sa.Column(
            "reconciled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_records_account_id"),
        "reconciliation_records",
        ["account_id"],
        unique=False,
    )
    op.add_column("accounts", sa.Column("institution_id", sa.Integer(), nullable=True))
    op.add_column("accounts", sa.Column("iban", sa.Text(), nullable=True))
    op.add_column("accounts", sa.Column("account_number", sa.Text(), nullable=True))
    op.add_column("accounts", sa.Column("account_tier", sa.Text(), nullable=True))
    op.add_column("accounts", sa.Column("branch", sa.Text(), nullable=True))
    op.create_foreign_key(None, "accounts", "financial_institutions", ["institution_id"], ["id"])
    op.drop_column("accounts", "institution")
    op.add_column(
        "categories",
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###

    # Partial unique indexes for financial_institutions
    op.create_index(
        "uq_institution_slug",
        "financial_institutions",
        ["slug"],
        unique=True,
        postgresql_where=text("household_id IS NULL AND is_active = true"),
    )
    op.create_index(
        "uq_custom_institution_slug",
        "financial_institutions",
        ["household_id", "slug"],
        unique=True,
        postgresql_where=text("household_id IS NOT NULL AND is_active = true"),
    )
    op.create_index(
        "uq_custom_institution_name_en",
        "financial_institutions",
        ["household_id", sa.text("lower(name_en)")],
        unique=True,
        postgresql_where=text("household_id IS NOT NULL AND is_active = true"),
    )
    op.create_index(
        "uq_custom_institution_name_ar",
        "financial_institutions",
        ["household_id", sa.text("lower(name_ar)")],
        unique=True,
        postgresql_where=text("household_id IS NOT NULL AND is_active = true"),
    )

    # Composite index for reconciliation lookups
    op.create_index(
        "idx_reconciliation_account",
        "reconciliation_records",
        ["account_id", sa.text("reconciled_at DESC")],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop custom indexes first
    op.drop_index("idx_reconciliation_account", table_name="reconciliation_records")
    op.drop_index("uq_custom_institution_name_ar", table_name="financial_institutions")
    op.drop_index("uq_custom_institution_name_en", table_name="financial_institutions")
    op.drop_index("uq_custom_institution_slug", table_name="financial_institutions")
    op.drop_index("uq_institution_slug", table_name="financial_institutions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "is_system")
    op.add_column(
        "accounts",
        sa.Column("institution", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("accounts_institution_id_fkey", "accounts", type_="foreignkey")
    op.drop_column("accounts", "branch")
    op.drop_column("accounts", "account_tier")
    op.drop_column("accounts", "account_number")
    op.drop_column("accounts", "iban")
    op.drop_column("accounts", "institution_id")
    op.drop_index(op.f("ix_reconciliation_records_account_id"), table_name="reconciliation_records")
    op.drop_table("reconciliation_records")
    op.drop_table("financial_institutions")
    # ### end Alembic commands ###
