"""add_import_templates

Revision ID: af900445891f
Revises: c3d4e5f6a7b2
Create Date: 2026-03-31 19:24:56.458964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af900445891f'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('date_format', sa.Text(), server_default='DD/MM/YYYY', nullable=False),
    sa.Column('encoding', sa.Text(), server_default='utf-8', nullable=False),
    sa.Column('skip_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sheet_name', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_templates_household_id'), 'import_templates', ['household_id'], unique=False)
    op.create_table('account_import_templates',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['import_templates.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_import_templates')
    op.drop_index(op.f('ix_import_templates_household_id'), table_name='import_templates')
    op.drop_table('import_templates')
    # ### end Alembic commands ###
